version: '3'

services:
  web:
    image: nginx:alpine
    restart: always
    depends_on:
      - php
    ports: 
      - '8080:80'
    volumes:
      - ./hello.php:/usr/local/lib/index.php
      - ./hello.conf:/etc/nginx/conf.d/default.conf 

  php:
    image: evfurman/php-fpm-pgsql:latest
    restart: always
    volumes:
      - ./hello.php:/usr/local/lib/index.php
