version: '3'

services:
  web:
    image: nginx:alpine
    ports: 
      - '8080:80'
    volumes:
      - ./hello.php:/usr/local/lib/index.php
      - ./hello.conf:/etc/nginx/conf.d/default.conf 

  php:
    image: php:fpm-alpine
    volumes:
      - ./hello.php:/usr/local/lib/index.php
